import * as stylex from '@stylexjs/stylex';

const focusRing = {
  outlineWidth: 3,
  outlineStyle: 'solid',
  outlineColor: 'color-mix(in srgb, var(--are-accent) 58%, transparent)',
  outlineOffset: 3,
} as const;

export const labStyles = stylex.create({
  page: {
    minHeight: '100dvh',
    color: 'var(--are-text)',
    backgroundColor: 'var(--are-bg)',
    backgroundImage: 'var(--are-page-background)',
    fontFamily: 'var(--are-font-body)',
  },
  topbar: {
    position: 'sticky',
    top: 0,
    zIndex: 20,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    minHeight: 76,
    paddingBlock: 12,
    paddingInline: {
      default: 24,
      '@media (max-width: 720px)': 14,
    },
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'color-mix(in srgb, var(--are-accent) 18%, transparent)',
    backgroundColor: 'color-mix(in srgb, var(--are-bg) 88%, transparent)',
    backdropFilter: 'blur(18px)',
    flexWrap: 'wrap',
    backgroundImage: 'var(--are-surface-texture)',
  },
  brand: {
    display: 'flex',
    alignItems: 'center',
    gap: 11,
    color: 'var(--are-text)',
    textDecoration: 'none',
    ':focus-visible': focusRing,
  },
  brandMark: {
    display: 'grid',
    placeItems: 'center',
    width: 42,
    height: 42,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--are-accent)',
    borderRadius: 11,
    color: 'var(--are-bg)',
    backgroundColor: 'var(--are-accent)',
    boxShadow: '0 0 28px color-mix(in srgb, var(--are-accent) 32%, transparent)',
    fontWeight: 950,
  },
  brandText: {
    display: 'grid',
    gap: 2,
    fontSize: 13,
    lineHeight: 1.1,
  },
  brandTextMeta: {
    color: 'var(--are-muted)',
    fontSize: 10,
    fontWeight: 750,
    letterSpacing: 0.5,
  },
  toolbar: {
    display: 'flex',
    gap: 8,
    flexWrap: 'wrap',
  },
  toolButton: {
    minHeight: 44,
    paddingBlock: 9,
    paddingInline: 12,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'color-mix(in srgb, var(--are-accent) 24%, transparent)',
    borderRadius: 10,
    color: 'var(--are-text)',
    backgroundColor: 'var(--are-surface)',
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 750,
    ':hover': {
      borderColor: 'var(--are-accent)',
    },
    ':focus-visible': focusRing,
  },
  themeSelect: {
    appearance: 'auto',
    minWidth: 196,
    fontFamily: 'var(--are-font-mono)',
  },
  resetButton: {
    minHeight: 44,
    paddingBlock: 9,
    paddingInline: 12,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'color-mix(in srgb, var(--are-danger) 42%, transparent)',
    borderRadius: 10,
    color: 'var(--are-danger)',
    backgroundColor: 'color-mix(in srgb, var(--are-danger) 8%, var(--are-surface))',
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 800,
    ':focus-visible': focusRing,
  },
  layout: {
    display: 'grid',
    gridTemplateColumns: {
      default: '220px minmax(0, 1fr) 240px',
      '@media (max-width: 1100px)': '210px minmax(0, 1fr)',
      '@media (max-width: 760px)': 'minmax(0, 1fr)',
    },
    gap: 18,
    width: 'min(1520px, 100%)',
    marginInline: 'auto',
    padding: {
      default: 20,
      '@media (max-width: 760px)': '12px 10px 24px',
    },
  },
  navigation: {
    position: {
      default: 'sticky',
      '@media (max-width: 760px)': 'static',
    },
    top: 96,
    display: 'flex',
    flexDirection: {
      default: 'column',
      '@media (max-width: 760px)': 'row',
    },
    gap: 6,
    alignSelf: 'start',
    maxWidth: {
      default: 'none',
      '@media (max-width: 760px)': '100%',
    },
    padding: 8,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'color-mix(in srgb, var(--are-accent) 12%, transparent)',
    borderRadius: 15,
    backgroundColor: 'color-mix(in srgb, var(--are-surface) 88%, transparent)',
    overflowX: {
      default: 'visible',
      '@media (max-width: 760px)': 'auto',
    },
    scrollbarWidth: 'thin',
  },
  navLink: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    minWidth: {
      default: 0,
      '@media (max-width: 760px)': 158,
    },
    minHeight: 44,
    paddingBlock: 9,
    paddingInline: 10,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'transparent',
    borderRadius: 9,
    color: 'var(--are-muted)',
    textDecoration: 'none',
    fontSize: 14,
    fontWeight: 720,
    ':hover': {
      color: 'var(--are-text)',
      borderColor: 'color-mix(in srgb, var(--are-accent) 20%, transparent)',
    },
    ':focus-visible': focusRing,
  },
  navLinkActive: {
    color: 'var(--are-text)',
    borderColor: 'color-mix(in srgb, var(--are-accent) 38%, transparent)',
    backgroundColor: 'var(--are-accent-soft)',
  },
  content: {
    minWidth: 0,
  },
  monitor: {
    position: 'sticky',
    top: 96,
    display: {
      default: 'grid',
      '@media (max-width: 1100px)': 'none',
    },
    gap: 14,
    alignSelf: 'start',
    padding: 15,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'color-mix(in srgb, var(--are-accent) 16%, transparent)',
    borderRadius: 15,
    backgroundColor: 'color-mix(in srgb, var(--are-surface) 90%, transparent)',
  },
  monitorHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  monitorLight: {
    width: 12,
    height: 12,
    borderRadius: '50%',
    backgroundColor: 'var(--are-warning)',
    boxShadow: '0 0 18px var(--are-warning)',
  },
  monitorLightActive: {
    backgroundColor: 'var(--are-success)',
    boxShadow: '0 0 20px var(--are-success)',
  },
  monitorStats: {
    display: 'grid',
    gap: 8,
    margin: 0,
    color: 'var(--are-muted)',
    fontSize: 13,
  },
  eventLog: {
    display: 'grid',
    gap: 7,
    maxHeight: 240,
    padding: 10,
    borderRadius: 10,
    color: 'var(--are-muted)',
    backgroundColor: 'color-mix(in srgb, var(--are-bg) 84%, black)',
    fontFamily: 'var(--are-font-mono)',
    fontSize: 12,
    lineHeight: 1.45,
    overflowY: 'auto',
  },
  overviewHeader: {
    display: 'grid',
    gridTemplateColumns: {
      default: '1.2fr .8fr',
      '@media (max-width: 850px)': '1fr',
    },
    alignItems: 'end',
    gap: 20,
    marginBottom: 18,
    padding: {
      default: '20px 10px 6px',
      '@media (max-width: 760px)': '12px 4px 4px',
    },
  },
  kicker: {
    margin: '0 0 7px',
    color: 'var(--are-accent)',
    fontFamily: 'var(--are-font-mono)',
    fontSize: 12,
    fontWeight: 900,
    letterSpacing: 1.4,
    textTransform: 'uppercase',
  },
  overviewTitle: {
    maxWidth: 760,
    margin: 0,
    fontSize: 'clamp(30px, 5vw, 54px)',
    lineHeight: 1,
    letterSpacing: '-0.04em',
    fontFamily: 'var(--are-font-display)',
    textShadow: 'var(--are-title-shadow)',
  },
  description: {
    maxWidth: 680,
    margin: 0,
    color: 'var(--are-muted)',
    fontSize: 16,
    lineHeight: 1.6,
  },
  catalog: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 245px), 1fr))',
    gap: 10,
  },
  catalogCard: {
    display: 'grid',
    gridTemplateColumns: 'auto 1fr auto',
    alignItems: 'center',
    gap: 12,
    minHeight: 92,
    padding: 14,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'color-mix(in srgb, var(--are-accent) 14%, transparent)',
    borderRadius: 15,
    color: 'var(--are-text)',
    backgroundColor: 'color-mix(in srgb, var(--are-surface) 92%, transparent)',
    textDecoration: 'none',
    transitionProperty: 'transform, border-color, background-color',
    transitionDuration: '150ms',
    ':hover': {
      transform: 'translateY(-2px)',
      borderColor: 'var(--are-accent)',
      backgroundColor: 'var(--are-surface-raised)',
    },
    ':focus-visible': focusRing,
    '@media (prefers-reduced-motion: reduce)': {
      transitionDuration: '0.01ms',
    },
  },
  catalogIndex: {
    display: 'grid',
    placeItems: 'center',
    width: 36,
    height: 36,
    borderRadius: 9,
    color: 'var(--are-accent)',
    backgroundColor: 'var(--are-accent-soft)',
    fontFamily: 'var(--are-font-mono)',
    fontSize: 12,
    fontWeight: 900,
  },
  catalogStatus: {
    color: 'var(--are-muted)',
    fontFamily: 'var(--are-font-mono)',
    fontSize: 11,
    fontWeight: 850,
    textTransform: 'uppercase',
  },
  workbench: {
    overflow: 'hidden',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'color-mix(in srgb, var(--are-accent) 16%, transparent)',
    borderRadius: {
      default: 22,
      '@media (max-width: 760px)': 16,
    },
    backgroundColor: 'color-mix(in srgb, var(--are-surface) 94%, transparent)',
    backgroundImage: 'var(--are-surface-texture)',
    boxShadow: '0 24px 90px rgba(0,0,0,.28)',
  },
  workbenchHeader: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 18,
    padding: {
      default: 22,
      '@media (max-width: 760px)': 15,
    },
  },
  workbenchTitle: {
    margin: '0 0 7px',
    fontSize: 'clamp(28px, 4vw, 46px)',
    lineHeight: 1,
    letterSpacing: '-0.035em',
    fontFamily: 'var(--are-font-display)',
    textShadow: 'var(--are-title-shadow)',
  },
  statusBadge: {
    flexShrink: 0,
    paddingBlock: 7,
    paddingInline: 10,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'color-mix(in srgb, var(--are-accent) 34%, transparent)',
    borderRadius: 999,
    color: 'var(--are-accent)',
    backgroundColor: 'var(--are-accent-soft)',
    fontFamily: 'var(--are-font-mono)',
    fontSize: 12,
    fontWeight: 900,
    textTransform: 'uppercase',
  },
  stage: {
    position: 'relative',
    display: 'grid',
    placeItems: 'stretch',
    minHeight: {
      default: 430,
      '@media (max-width: 760px)': 330,
    },
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderStyle: 'solid',
    borderColor: 'color-mix(in srgb, var(--are-accent) 12%, transparent)',
    backgroundImage: 'var(--are-stage-background)',
  },
  domStage: {
    display: 'grid',
    alignContent: 'center',
    width: 'min(720px, calc(100% - 28px))',
    margin: 'auto',
    paddingBlock: 24,
  },
  instructionPanel: {
    display: 'grid',
    gridTemplateColumns: {
      default: 'minmax(220px, 1fr) auto',
      '@media (max-width: 760px)': '1fr',
    },
    alignItems: 'center',
    gap: 16,
    padding: {
      default: '17px 22px',
      '@media (max-width: 760px)': 14,
    },
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'color-mix(in srgb, var(--are-accent) 12%, transparent)',
  },
  sectionLabel: {
    margin: '0 0 5px',
    color: 'var(--are-accent)',
    fontFamily: 'var(--are-font-mono)',
    fontSize: 12,
    fontWeight: 900,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  instruction: {
    margin: 0,
    color: 'var(--are-text)',
    fontSize: 15,
    lineHeight: 1.5,
  },
  controls: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: {
      default: 'flex-end',
      '@media (max-width: 760px)': 'stretch',
    },
    gap: 8,
    flexWrap: 'wrap',
  },
  controlButton: {
    minWidth: 48,
    minHeight: 48,
    paddingBlock: 9,
    paddingInline: 13,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'color-mix(in srgb, var(--are-accent) 32%, transparent)',
    borderRadius: 11,
    color: 'var(--are-text)',
    backgroundColor: 'var(--are-surface-raised)',
    cursor: 'pointer',
    fontSize: 16,
    fontWeight: 850,
    touchAction: 'manipulation',
    ':hover': {
      borderColor: 'var(--are-accent)',
      boxShadow: '0 0 20px color-mix(in srgb, var(--are-accent) 15%, transparent)',
    },
    ':focus-visible': focusRing,
  },
  controlReadout: {
    display: 'grid',
    placeItems: 'center',
    minWidth: 58,
    minHeight: 48,
    color: 'var(--are-accent)',
    fontFamily: 'var(--are-font-mono)',
    fontSize: 18,
    fontWeight: 900,
  },
  keypadControls: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(54px, 1fr))',
    gap: 7,
    width: 'min(300px, 100%)',
  },
  slider: {
    width: {
      default: 190,
      '@media (max-width: 760px)': '100%',
    },
    minHeight: 44,
    accentColor: 'var(--are-accent)',
  },
  rotorControls: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(72px, 1fr))',
    gap: 8,
    width: 'min(360px, 100%)',
  },
  rotorColumn: {
    display: 'grid',
    gridTemplateRows: '48px 36px 48px',
    gap: 5,
  },
  detailGrid: {
    display: 'grid',
    gridTemplateColumns: {
      default: 'repeat(2, minmax(0, 1fr))',
      '@media (max-width: 760px)': '1fr',
    },
    gap: 1,
    backgroundColor: 'color-mix(in srgb, var(--are-accent) 12%, transparent)',
  },
  detailPanel: {
    padding: {
      default: 20,
      '@media (max-width: 760px)': 14,
    },
    backgroundColor: 'var(--are-surface)',
  },
  solution: {
    margin: 0,
    color: 'var(--are-text)',
    fontSize: 15,
    fontWeight: 750,
    lineHeight: 1.55,
  },
  telemetry: {
    marginTop: 12,
    color: 'var(--are-muted)',
    fontFamily: 'var(--are-font-mono)',
    fontSize: 13,
  },
  hints: {
    display: 'grid',
    gap: 7,
    margin: 0,
    paddingLeft: 20,
    color: 'var(--are-muted)',
    fontSize: 14,
    lineHeight: 1.5,
  },
  accessibility: {
    margin: 0,
    padding: {
      default: '14px 20px 18px',
      '@media (max-width: 760px)': 14,
    },
    color: 'var(--are-muted)',
    backgroundColor: 'var(--are-surface)',
    fontSize: 14,
    lineHeight: 1.5,
  },
  statusRow: {
    display: 'flex',
    gap: 8,
    flexWrap: 'wrap',
  },
});
