import * as stylex from '@stylexjs/stylex';

const focusRing = {
  outlineWidth: 3,
  outlineStyle: 'solid',
  outlineColor: 'color-mix(in srgb, var(--are-accent) 68%, transparent)',
  outlineOffset: 3,
} as const;

export const labStyles = stylex.create({
  page: {
    minHeight: '100dvh',
    color: 'var(--are-text)',
    backgroundColor: 'var(--are-bg)',
    backgroundImage: [
      'radial-gradient(circle at 8% -12%, color-mix(in srgb, var(--are-accent) 18%, transparent), transparent 30rem)',
      'linear-gradient(color-mix(in srgb, var(--are-accent) 4%, transparent) 1px, transparent 1px)',
      'linear-gradient(90deg, color-mix(in srgb, var(--are-accent) 4%, transparent) 1px, transparent 1px)',
      'linear-gradient(180deg, color-mix(in srgb, var(--are-bg) 86%, #172636), var(--are-bg))',
    ].join(','),
    backgroundSize: 'auto, 36px 36px, 36px 36px, auto',
    fontFamily: 'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
  },
  topbar: {
    position: 'sticky',
    top: 0,
    zIndex: 20,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    minHeight: 74,
    paddingBlock: 12,
    paddingInline: {
      default: 28,
      '@media (max-width: 720px)': 14,
    },
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'color-mix(in srgb, var(--are-accent) 24%, transparent)',
    backgroundColor: 'color-mix(in srgb, var(--are-bg) 86%, transparent)',
    backdropFilter: 'blur(20px)',
    flexWrap: 'wrap',
  },
  brand: {
    display: 'flex',
    alignItems: 'center',
    gap: 11,
    color: 'var(--are-text)',
    textDecoration: 'none',
    ':focus-visible': focusRing,
  },
  brandMark: {
    display: 'grid',
    placeItems: 'center',
    width: 42,
    height: 42,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--are-accent)',
    borderRadius: 12,
    color: 'var(--are-bg)',
    backgroundColor: 'var(--are-accent)',
    boxShadow: '0 0 28px color-mix(in srgb, var(--are-accent) 32%, transparent)',
    fontSize: 18,
    fontWeight: 950,
  },
  brandText: {
    display: 'grid',
    gap: 2,
    fontSize: 13,
    letterSpacing: 0.9,
    lineHeight: 1.1,
  },
  brandTextMeta: {
    color: 'var(--are-muted)',
    fontSize: 10,
    fontWeight: 750,
    letterSpacing: 0.5,
  },
  toolbar: {
    display: 'flex',
    gap: 8,
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
  },
  toolButton: {
    minHeight: 44,
    paddingBlock: 9,
    paddingInline: 12,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'color-mix(in srgb, var(--are-accent) 24%, transparent)',
    borderRadius: 10,
    color: 'var(--are-text)',
    backgroundColor: 'var(--are-surface)',
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 750,
    touchAction: 'manipulation',
    ':hover': {
      borderColor: 'var(--are-accent)',
    },
    ':focus-visible': focusRing,
  },
  resetButton: {
    minHeight: 44,
    paddingBlock: 9,
    paddingInline: 12,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'color-mix(in srgb, var(--are-danger) 42%, transparent)',
    borderRadius: 10,
    color: 'var(--are-danger)',
    backgroundColor: 'color-mix(in srgb, var(--are-danger) 8%, var(--are-surface))',
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 800,
    touchAction: 'manipulation',
    ':focus-visible': focusRing,
  },
  layout: {
    display: 'grid',
    gridTemplateColumns: {
      default: '232px minmax(0, 1fr) 254px',
      '@media (max-width: 1160px)': '216px minmax(0, 1fr)',
      '@media (max-width: 760px)': 'minmax(0, 1fr)',
    },
    gap: {
      default: 20,
      '@media (max-width: 760px)': 12,
    },
    width: 'min(1640px, 100%)',
    marginInline: 'auto',
    padding: {
      default: '22px 20px 34px',
      '@media (max-width: 760px)': '12px 10px 26px',
    },
  },
  navigation: {
    position: {
      default: 'sticky',
      '@media (max-width: 760px)': 'static',
    },
    top: 94,
    display: 'grid',
    gap: 6,
    alignSelf: 'start',
    maxWidth: '100%',
    padding: 9,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'color-mix(in srgb, var(--are-accent) 12%, transparent)',
    borderRadius: 17,
    backgroundColor: 'color-mix(in srgb, var(--are-surface) 90%, transparent)',
    boxShadow: '0 18px 50px rgba(0,0,0,.18)',
    overflow: 'hidden',
  },
  navigationHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    padding: '5px 7px 9px',
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'color-mix(in srgb, var(--are-accent) 12%, transparent)',
  },
  navigationTitle: {
    margin: 0,
    color: 'var(--are-text)',
    fontSize: 11,
    fontWeight: 900,
    letterSpacing: 1.1,
    textTransform: 'uppercase',
  },
  navigationCount: {
    color: 'var(--are-muted)',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
    fontSize: 10,
  },
  navLink: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    minWidth: 0,
    minHeight: 44,
    paddingBlock: 9,
    paddingInline: 10,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'transparent',
    borderRadius: 9,
    color: 'var(--are-muted)',
    textDecoration: 'none',
    fontSize: 13,
    fontWeight: 760,
    ':hover': {
      color: 'var(--are-text)',
      borderColor: 'color-mix(in srgb, var(--are-accent) 26%, transparent)',
      backgroundColor: 'color-mix(in srgb, var(--are-accent) 6%, transparent)',
    },
    ':focus-visible': focusRing,
  },
  navLinkActive: {
    color: 'var(--are-text)',
    borderColor: 'color-mix(in srgb, var(--are-accent) 46%, transparent)',
    backgroundColor: 'var(--are-accent-soft)',
    boxShadow: 'inset 3px 0 0 var(--are-accent)',
  },
  navLinkStatus: {
    color: 'var(--are-muted)',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
    fontSize: 10,
    fontWeight: 850,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  navLinkStatusSolved: {
    color: 'var(--are-success)',
  },
  content: {
    minWidth: 0,
  },
  monitor: {
    position: 'sticky',
    top: 94,
    display: {
      default: 'grid',
      '@media (max-width: 1160px)': 'none',
    },
    gap: 15,
    alignSelf: 'start',
    padding: 16,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'color-mix(in srgb, var(--are-accent) 16%, transparent)',
    borderRadius: 17,
    backgroundColor: 'color-mix(in srgb, var(--are-surface) 92%, transparent)',
    boxShadow: '0 18px 50px rgba(0,0,0,.18)',
  },
  monitorHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  monitorIdentity: {
    display: 'grid',
    gap: 3,
    minWidth: 0,
  },
  monitorIdentityValue: {
    overflow: 'hidden',
    color: 'var(--are-text)',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
    fontSize: 11,
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  monitorLight: {
    width: 12,
    height: 12,
    borderRadius: '50%',
    backgroundColor: 'var(--are-warning)',
    boxShadow: '0 0 18px var(--are-warning)',
  },
  monitorLightActive: {
    backgroundColor: 'var(--are-success)',
    boxShadow: '0 0 20px var(--are-success)',
  },
  monitorStats: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    gap: 7,
    margin: 0,
  },
  monitorStat: {
    display: 'grid',
    gap: 4,
    padding: 9,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'color-mix(in srgb, var(--are-accent) 12%, transparent)',
    borderRadius: 10,
    backgroundColor: 'color-mix(in srgb, var(--are-bg) 74%, transparent)',
  },
  monitorStatLabel: {
    color: 'var(--are-muted)',
    fontSize: 10,
    fontWeight: 750,
  },
  monitorStatValue: {
    color: 'var(--are-text)',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
    fontSize: 16,
    fontWeight: 900,
  },
  monitorProgress: {
    display: 'grid',
    gap: 7,
  },
  monitorProgressHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: 8,
    color: 'var(--are-muted)',
    fontSize: 11,
    fontWeight: 760,
  },
  monitorProgressBar: {
    width: '100%',
    height: 7,
    overflow: 'hidden',
    border: 0,
    borderRadius: 99,
    backgroundColor: 'color-mix(in srgb, var(--are-bg) 78%, black)',
    accentColor: 'var(--are-accent)',
  },
  eventLog: {
    display: 'grid',
    gap: 7,
    maxHeight: 244,
    padding: 10,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'color-mix(in srgb, var(--are-accent) 12%, transparent)',
    borderRadius: 10,
    color: 'var(--are-muted)',
    backgroundColor: 'color-mix(in srgb, var(--are-bg) 84%, black)',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
    fontSize: 11,
    lineHeight: 1.45,
    overflowY: 'auto',
  },
  overviewHeader: {
    display: 'grid',
    gridTemplateColumns: {
      default: '1.2fr .8fr',
      '@media (max-width: 880px)': '1fr',
    },
    alignItems: 'end',
    gap: 24,
    marginBottom: 18,
    padding: {
      default: '22px 8px 20px',
      '@media (max-width: 760px)': '12px 4px 16px',
    },
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'color-mix(in srgb, var(--are-accent) 14%, transparent)',
  },
  overviewCopy: {
    display: 'grid',
    gap: 0,
  },
  kicker: {
    margin: '0 0 8px',
    color: 'var(--are-accent)',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
    fontSize: 11,
    fontWeight: 900,
    letterSpacing: 1.4,
    textTransform: 'uppercase',
  },
  overviewTitle: {
    maxWidth: 780,
    margin: 0,
    fontSize: 'clamp(32px, 5vw, 60px)',
    lineHeight: 0.98,
    letterSpacing: '-0.055em',
  },
  description: {
    maxWidth: 680,
    margin: 0,
    color: 'var(--are-muted)',
    fontSize: 15,
    lineHeight: 1.65,
  },
  overviewSummary: {
    display: 'grid',
    gap: 13,
    padding: 15,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'color-mix(in srgb, var(--are-accent) 22%, transparent)',
    borderRadius: 15,
    backgroundColor: 'color-mix(in srgb, var(--are-surface) 84%, transparent)',
  },
  overviewSummaryLabel: {
    margin: 0,
    color: 'var(--are-accent)',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
    fontSize: 11,
    fontWeight: 900,
    letterSpacing: 1.1,
    textTransform: 'uppercase',
  },
  overviewSummaryText: {
    margin: 0,
    color: 'var(--are-text)',
    fontSize: 14,
    lineHeight: 1.55,
  },
  overviewStats: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    gap: 8,
    marginTop: 18,
  },
  overviewStat: {
    display: 'grid',
    gap: 4,
    padding: 11,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'color-mix(in srgb, var(--are-accent) 12%, transparent)',
    borderRadius: 12,
    backgroundColor: 'color-mix(in srgb, var(--are-surface) 88%, transparent)',
  },
  overviewStatValue: {
    color: 'var(--are-text)',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
    fontSize: 20,
    fontWeight: 900,
  },
  overviewStatLabel: {
    color: 'var(--are-muted)',
    fontSize: 11,
    fontWeight: 760,
  },
  catalog: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 280px), 1fr))',
    gap: 12,
  },
  catalogCard: {
    display: 'grid',
    gap: 13,
    minHeight: 158,
    padding: 16,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'color-mix(in srgb, var(--are-accent) 14%, transparent)',
    borderRadius: 16,
    color: 'var(--are-text)',
    backgroundColor: 'color-mix(in srgb, var(--are-surface) 92%, transparent)',
    textDecoration: 'none',
    boxShadow: '0 14px 32px rgba(0,0,0,.12)',
    transitionProperty: 'transform, border-color, background-color, box-shadow',
    transitionDuration: '160ms',
    ':hover': {
      transform: 'translateY(-2px)',
      borderColor: 'var(--are-accent)',
      backgroundColor: 'var(--are-surface-raised)',
      boxShadow: '0 18px 42px rgba(0,0,0,.24)',
    },
    ':focus-visible': focusRing,
    '@media (prefers-reduced-motion: reduce)': {
      transitionDuration: '0.01ms',
    },
  },
  catalogCardSolved: {
    borderColor: 'color-mix(in srgb, var(--are-success) 48%, transparent)',
  },
  catalogCardHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  catalogIndex: {
    display: 'grid',
    placeItems: 'center',
    width: 38,
    height: 38,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'color-mix(in srgb, var(--are-accent) 28%, transparent)',
    borderRadius: 10,
    color: 'var(--are-accent)',
    backgroundColor: 'var(--are-accent-soft)',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
    fontSize: 12,
    fontWeight: 900,
  },
  catalogStatus: {
    paddingBlock: 5,
    paddingInline: 8,
    borderRadius: 99,
    color: 'var(--are-muted)',
    backgroundColor: 'color-mix(in srgb, var(--are-bg) 74%, transparent)',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
    fontSize: 11,
    fontWeight: 850,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  catalogStatusSolved: {
    color: 'var(--are-success)',
    backgroundColor: 'color-mix(in srgb, var(--are-success) 12%, transparent)',
  },
  catalogCopy: {
    display: 'grid',
    gap: 4,
  },
  catalogTitle: {
    fontSize: 16,
    lineHeight: 1.15,
  },
  catalogArtifact: {
    color: 'var(--are-accent)',
    fontSize: 11,
    fontWeight: 820,
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  catalogDescription: {
    display: '-webkit-box',
    WebkitBoxOrient: 'vertical',
    WebkitLineClamp: 2,
    overflow: 'hidden',
    margin: 0,
    color: 'var(--are-muted)',
    fontSize: 13,
    lineHeight: 1.45,
  },
  catalogFooter: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    marginTop: 'auto',
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: 'color-mix(in srgb, var(--are-accent) 10%, transparent)',
  },
  catalogFamily: {
    color: 'var(--are-muted)',
    fontSize: 11,
    fontWeight: 740,
  },
  catalogAction: {
    color: 'var(--are-accent)',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
    fontSize: 10,
    fontWeight: 900,
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  workbench: {
    overflow: 'hidden',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'color-mix(in srgb, var(--are-accent) 20%, transparent)',
    borderRadius: {
      default: 23,
      '@media (max-width: 760px)': 17,
    },
    backgroundColor: 'color-mix(in srgb, var(--are-surface) 94%, transparent)',
    boxShadow: '0 24px 90px rgba(0,0,0,.28)',
  },
  workbenchHeader: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) auto',
    alignItems: 'start',
    gap: 18,
    padding: {
      default: 24,
      '@media (max-width: 760px)': 16,
    },
  },
  workbenchTitle: {
    margin: '0 0 8px',
    fontSize: 'clamp(29px, 4vw, 48px)',
    lineHeight: 0.98,
    letterSpacing: '-0.045em',
  },
  workbenchHeaderMeta: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
    marginTop: 12,
  },
  workbenchMeta: {
    paddingBlock: 5,
    paddingInline: 8,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'color-mix(in srgb, var(--are-accent) 18%, transparent)',
    borderRadius: 99,
    color: 'var(--are-muted)',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
    fontSize: 10,
    fontWeight: 800,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  statusBadge: {
    flexShrink: 0,
    paddingBlock: 8,
    paddingInline: 10,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'color-mix(in srgb, var(--are-accent) 34%, transparent)',
    borderRadius: 999,
    color: 'var(--are-accent)',
    backgroundColor: 'var(--are-accent-soft)',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
    fontSize: 11,
    fontWeight: 900,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  statusBadgeSolved: {
    color: 'var(--are-success)',
    borderColor: 'color-mix(in srgb, var(--are-success) 42%, transparent)',
    backgroundColor: 'color-mix(in srgb, var(--are-success) 11%, transparent)',
  },
  statusBadgeError: {
    color: 'var(--are-danger)',
    borderColor: 'color-mix(in srgb, var(--are-danger) 42%, transparent)',
    backgroundColor: 'color-mix(in srgb, var(--are-danger) 11%, transparent)',
  },
  stageLead: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    paddingInline: {
      default: 24,
      '@media (max-width: 760px)': 16,
    },
    paddingBottom: 10,
  },
  stageLeadLabel: {
    color: 'var(--are-accent)',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
    fontSize: 10,
    fontWeight: 900,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  stageLeadRule: {
    height: 1,
    flex: 1,
    backgroundColor: 'color-mix(in srgb, var(--are-accent) 18%, transparent)',
  },
  stage: {
    position: 'relative',
    display: 'grid',
    placeItems: 'stretch',
    minHeight: {
      default: 430,
      '@media (max-width: 760px)': 330,
    },
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderStyle: 'solid',
    borderColor: 'color-mix(in srgb, var(--are-accent) 15%, transparent)',
    backgroundImage: [
      'radial-gradient(circle at 50% 45%, color-mix(in srgb, var(--are-accent) 16%, transparent), transparent 44%)',
      'linear-gradient(180deg, color-mix(in srgb, var(--are-bg) 80%, #142433), var(--are-bg))',
    ].join(','),
  },
  domStage: {
    display: 'grid',
    alignContent: 'center',
    width: 'min(760px, calc(100% - 32px))',
    margin: 'auto',
    paddingBlock: 28,
    '@media (max-width: 760px)': {
      width: 'min(100%, calc(100% - 20px))',
      paddingBlock: 18,
    },
  },
  instructionPanel: {
    display: 'grid',
    gridTemplateColumns: {
      default: 'minmax(220px, 1fr) auto',
      '@media (max-width: 760px)': '1fr',
    },
    alignItems: 'center',
    gap: 16,
    padding: {
      default: '18px 24px',
      '@media (max-width: 760px)': 14,
    },
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'color-mix(in srgb, var(--are-accent) 12%, transparent)',
    backgroundColor: 'color-mix(in srgb, var(--are-surface-raised) 48%, transparent)',
  },
  instructionCopy: {
    display: 'grid',
    gap: 2,
  },
  sectionLabel: {
    margin: '0 0 5px',
    color: 'var(--are-accent)',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
    fontSize: 11,
    fontWeight: 900,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  instruction: {
    margin: 0,
    color: 'var(--are-text)',
    fontSize: 15,
    lineHeight: 1.5,
  },
  controls: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: {
      default: 'flex-end',
      '@media (max-width: 760px)': 'stretch',
    },
    gap: 8,
    flexWrap: 'wrap',
  },
  controlButton: {
    minWidth: 48,
    minHeight: 48,
    paddingBlock: 9,
    paddingInline: 13,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'color-mix(in srgb, var(--are-accent) 32%, transparent)',
    borderRadius: 11,
    color: 'var(--are-text)',
    backgroundColor: 'var(--are-surface-raised)',
    cursor: 'pointer',
    fontSize: 16,
    fontWeight: 850,
    touchAction: 'manipulation',
    ':hover': {
      borderColor: 'var(--are-accent)',
      boxShadow: '0 0 20px color-mix(in srgb, var(--are-accent) 15%, transparent)',
    },
    ':focus-visible': focusRing,
    ':disabled': {
      cursor: 'default',
      opacity: 0.5,
    },
  },
  controlReadout: {
    display: 'grid',
    placeItems: 'center',
    minWidth: 58,
    minHeight: 48,
    color: 'var(--are-accent)',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
    fontSize: 18,
    fontWeight: 900,
  },
  keypadControls: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(54px, 1fr))',
    gap: 7,
    width: 'min(300px, 100%)',
  },
  slider: {
    width: {
      default: 190,
      '@media (max-width: 760px)': 'min(100%, 230px)',
    },
    minHeight: 44,
    accentColor: 'var(--are-accent)',
  },
  rotorControls: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(72px, 1fr))',
    gap: 8,
    width: 'min(360px, 100%)',
  },
  rotorColumn: {
    display: 'grid',
    gridTemplateRows: '48px 36px 48px',
    gap: 5,
  },
  detailGrid: {
    display: 'grid',
    gridTemplateColumns: {
      default: 'repeat(2, minmax(0, 1fr))',
      '@media (max-width: 760px)': '1fr',
    },
    gap: 1,
    backgroundColor: 'color-mix(in srgb, var(--are-accent) 13%, transparent)',
  },
  detailPanel: {
    minWidth: 0,
    padding: {
      default: 21,
      '@media (max-width: 760px)': 14,
    },
    backgroundColor: 'var(--are-surface)',
  },
  detailPanelHeader: {
    display: 'flex',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 10,
  },
  solution: {
    margin: 0,
    color: 'var(--are-text)',
    fontSize: 15,
    fontWeight: 750,
    lineHeight: 1.55,
  },
  telemetry: {
    marginTop: 12,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: 'color-mix(in srgb, var(--are-accent) 12%, transparent)',
    color: 'var(--are-muted)',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
    fontSize: 12,
  },
  hints: {
    display: 'grid',
    gap: 9,
    margin: 0,
    paddingLeft: 0,
    listStyle: 'none',
    color: 'var(--are-muted)',
    fontSize: 14,
    lineHeight: 1.5,
  },
  hintItem: {
    display: 'grid',
    gridTemplateColumns: '26px minmax(0, 1fr)',
    alignItems: 'start',
    gap: 8,
  },
  hintNumber: {
    display: 'grid',
    placeItems: 'center',
    width: 24,
    height: 24,
    borderRadius: 8,
    color: 'var(--are-accent)',
    backgroundColor: 'var(--are-accent-soft)',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
    fontSize: 11,
    fontWeight: 900,
  },
  accessibility: {
    margin: 0,
    padding: {
      default: '15px 21px 19px',
      '@media (max-width: 760px)': 14,
    },
    color: 'var(--are-muted)',
    backgroundColor: 'var(--are-surface)',
    fontSize: 13,
    lineHeight: 1.55,
  },
  statusRow: {
    display: 'flex',
    gap: 8,
    flexWrap: 'wrap',
  },
});
